version: "3"
services:
  mysql-container:
    image: "mysql:latest"
    ports:
      - "33061:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_USER: 'root'
  eureka-container:
    restart: always
    image: "pixalquarks/bookingsystemdiscoveryservice:master"
    ports:
      - "8761:8761"
  api-gateway:
    restart: always
    image: "pixalquarks/bookingsystemapigateway:master"
    ports:
      - "9000:9000"


