version: "3"
services:
  mysql-container:
    image: "mysql:latest"
    ports:
      - "33061:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_USER: 'root'
  eureka-container:
    restart: always
    image: "pixalquarks/bookingsystemdiscoveryservice:master"
    ports:
      - "8761:8761"
  api-gateway:
    restart: always
    image: "pixalquarks/bookingsystemapigateway:master"
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_JSON: '{
        "eureka.client.service-url.defaultZone" : "http://eureka-container:8761/eureka/"
      }'
  city-service:
    depends_on:
      - mysql-container
      - eureka-container
      - api-gateway
    image: "pixalquarks/bookingsystemcityservice:master"
    environment:
      SPRING_APPLICATION_JSON: '{
         "eureka.client.service-url.defaultZone" : "http://eureka-container:8761/eureka/",
         "spring.datasource.username" : "root",
         "spring.datasource.password" : "root",
         "spring.datasource.url" : "jdbc:mysql://mysql-container:3306/city-db?createDatabaseIfNotExist=true"
      }'



