version: "3"
services:
  eureka-container:
    restart: always
    image: "pixalquarks/bookingsystemdiscoveryservice:master"
    hostname: eureka-container
    mem_limit: 300m
    ports:
      - "8761:8761"
  api-gateway:
    depends_on:
      - eureka-container
    restart: always
    image: "pixalquarks/bookingsystemapigateway:master"
    mem_limit: 300m
    hostname: api-gateway
    ports:
      - "9000:9000"
    environment:
     SPRING_APPLICATION_JSON: '{
        "server.ssl.enabled" : false,
        "server.ssl.client-auth" : "none",
        "eureka.client.service-url.defaultZone" : "http://eureka-container:8761/eureka/",
        "server.ssl.keystore" : "classpath:keystore/dockerPlayKeystore.p12"
      }'
  city-service:
    depends_on:
      - eureka-container
      - api-gateway
    image: "pixalquarks/bookingsystemcityservice:master"
    mem_limit: 300m
    hostname: city-service
    environment:
      SPRING_PROFILES_ACTIVE: aws
  # movie-service:
  #   depends_on:
  #     - api-gateway
  #     - eureka-container
  #   image: "pixalquarks/bookingsystemmovieservice:master"
  #   mem_limit: 200m
  #   hostname: movie-service
  #   environment:
  #     SPRING_PROFILES_ACTIVE: aws
  # theatre-service:
  #   depends_on:
  #     - api-gateway
  #     - eureka-container
  #   image: "pixalquarks/bookingsystemtheatreservice:master"
  #   mem_limit: 200m
  #   hostname: theatre-service
  #   environment:
  #     SPRING_PROFILES_ACTIVE: aws
  # booking-service:
  #   depends_on:
  #     - api-gateway
  #     - eureka-container
  #   image: "pixalquarks/bookingsystembookingservice:master"
  #   mem_limit: 200m
  #   hostname: booking-service
  #   environment:
  #     SPRING_PROFILES_ACTIVE: aws
  authentication-service:
    depends_on:
      - eureka-container
    image: "pixalquarks/bookingsystemauthenticationservice:master"
    mem_limit: 300m
    hostname: authentication-service
    environment:
      SPRING_PROFILES_ACTIVE: aws


