spring:
  application:
    name: theatre-service
  datasource:
    url: jdbc:mysql://localhost:3306/theatre-db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 0
  servlet:
    context-path: /api/v1/movie-booking/theatre

logging:
  level:
    "*": INFO
  file:
    path: .
    name: application.log

eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
