name : Build ApiGateway Docker Image
on:
  push:
    branches: ["master"]
    paths:
      - "Apigateway/*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup jdk 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: change to /ApiGateway
        run: cd /ApiGateway
      - name: Build with maven
        run: maven clean install -DskipTests
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: jars
          path: target/*jar
  deployDockerImage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          name: jars
      - name: docker login action
        uses: docker/login-action@1.14.1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: extract metadata
        id: meta
        uses: docker/metadata-actions@v3.5.0
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/${ secrets.DOCKER_API_GATEWAY_REPOSITORY }}
      - name: build and push
        uses: docker/build-push-action@v3.0.0
        with:
          context: ./ApiGateway
          push: true
          tags: ${{ steps.meta.output.tags }}
          labels: ${{ steps.meta.output.labels }}