name : Build DiscoveryService Docker Image
on:
  push:
    branches: ["master"]
    paths:
      - "DiscoveryService/*"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup jdk 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with maven
        run: mvn --projects DiscoveryService -am clean install -DskipTests
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: jars
          path: ./DiscoveryService/target/*.jar
  deployDockerContainer:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          name: jars
      - name: docker login action
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: extract metadata
        id: meta1
        uses: docker/metadata-action@v3.5.0
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_DISCOVERY_SERVICE_REPOSITORY }}
      - name: build and push
        uses: docker/build-push-action@v3.0.0
        with:
          context: ./DiscoveryService
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
